package cn.lijuntao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-01T17:40:46.573+08:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://service.axis2.lijuntao.cn", name = "TestServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface TestServicePortType {

    @WebMethod(action = "urn:sayGoodbye")
    @Action(input = "urn:sayGoodbye", output = "urn:sayGoodbyeResponse")
    @RequestWrapper(localName = "sayGoodbye", targetNamespace = "http://service.axis2.lijuntao.cn", className = "cn.lijuntao.SayGoodbye")
    @ResponseWrapper(localName = "sayGoodbyeResponse", targetNamespace = "http://service.axis2.lijuntao.cn", className = "cn.lijuntao.SayGoodbyeResponse")
    @WebResult(name = "return", targetNamespace = "http://service.axis2.lijuntao.cn")
    public java.lang.String sayGoodbye(
        @WebParam(name = "name", targetNamespace = "http://service.axis2.lijuntao.cn")
        java.lang.String name
    );

    @WebMethod(action = "urn:sayHello")
    @Action(input = "urn:sayHello", output = "urn:sayHelloResponse")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.axis2.lijuntao.cn", className = "cn.lijuntao.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.axis2.lijuntao.cn", className = "cn.lijuntao.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "http://service.axis2.lijuntao.cn")
    public java.lang.String sayHello(
        @WebParam(name = "name", targetNamespace = "http://service.axis2.lijuntao.cn")
        java.lang.String name
    );
}
